---
abstract: 'use DBIx::Simple::Class in your application.'
author:
  - 'Красимир Беров <berov@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-DSC
no_index:
  directory:
    - t
    - inc
requires:
  DBIx::Simple::Class: 0.62
  Mojolicious: 2.0
version: 0.05
